export const products = [
    {
        id: 1,
        name: "courvoisier",
        price: 93160165.38,
        image: "Asstes/imagenes/21 botellas.png",
    },
    {
        id: 2,
        name: "Remy martin",
        price: 8274332.47,
        image: "Asstes/imagenes/29 botella.jpg",
    },
    {
        id: 3,
        name: "martell",
        price: 8610861.05,
        image: "Asstes/imagenes/Botella dos.jpg",
    },
    {
        id: 4,
        name: "Louis Xlll",
        price: 27127620.30,
        image: "Asstes/imagenes/Botella 3.jpg",
    },
    {
        id: 5,
        name: "Carlos lll",
        price: 120000.00,
        image: "Asstes/imagenes/Cuarta botella.jpg",
    },
    {
        id: 6,
        name: "REMY MARTI",
        price: 14313568.50,
        image: "Asstes/imagenes/Quinto botella.jpg",
    },
    {
        id: 7,
        name: "ARMAGNAC SEMPE",
        price: 13132131.10,
        image: "Asstes/imagenes/Sexto botella.jpg",
    },
    {
        id: 8,
        name: "Hennessy",
        price: 21783888.06,
        image: "Asstes/imagenes/Séptima botella.png",
    },
    {
        id: 9,
        name: "REMY MARTIN",
        price: 12990000.00,
        image: "Asstes/imagenes/Octavo botella.png",
    },
    {
        id: 10,
        name: "Hennessy X.O",
        price: 5043828.90,
        image: "Asstes/imagenes/Novena botella.jpg",
    },
    {
        id: 11,
        name: "LARSEN V.S.O.P",
        price: 41436644.81,
        image: "Asstes/imagenes/Décima botella.jpg",
    },
    {
        id: 12,
        name: "XANTE LIQUEOR",
        price: 112841236.14,
        image: "Asstes/imagenes/11 botellas.jpg",
    },
    {
        id: 13,
        name: "CARLOS I DESDE 1889",
        price: 21463501.50,
        image: "Asstes/imagenes/12 botellas.jpg",
    },
    {
        id: 14,
        name: "RICHARD HENNESS",
        price: 21776936.76,
        image: "Asstes/imagenes/13 botellas.jpg",
    },
    {
        id: 15,
        name: "COMTE JOSEPH",
        price: 19246741.98,
        image: "Asstes/imagenes/14 botellas.gif",
    },
    {
        id: 16,
        name: "COMTE JOSEPH",
        price: 1300000.00,
        image: "Asstes/imagenes/15 botellas.jpg",
    },
    {
        id: 17,
        name: "ZACAPA",
        price: 15224477.00,
        image: "Asstes/imagenes/27 botellas.jpg",
    },
    {
        id: 18,
        name: "Hennessy",
        price: 4680958.60,
        image: "Asstes/imagenes/20 botellas.png",
    },
    {
        id: 19,
        name: "Mistial",
        price: 15291939.65,
        image: "Asstes/imagenes/26 botellas.jpg",
    },
    {
        id: 20,
        name: "Henness",
        price: 147277500.34,
        image: "Asstes/imagenes/23 botellas.jpeg",
    },
];